-- 初始化数据脚本，也可以用hibernate制动生成
CREATE TABLE ACT_QINGJIA (
        QID BIGINT NOT NULL AUTO_INCREMENT,
        DAYS BIGINT,
        USER_NAME VARCHAR(100),
        REMARK VARCHAR(100),
        DATA_TM DATETIME,
        FLOW_ID VARCHAR(100),
        PRIMARY KEY (QID)
    ) ENGINE=INNODB DEFAULT CHARSET=utf8;
    
     CREATE TABLE ACT_QINGJIA_HIS (
        HID BIGINT NOT NULL AUTO_INCREMENT,
        QID BIGINT,
        SHENPI_ACTION VARCHAR(100),
        SHENPI_REMARK VARCHAR(100),
        DATA_TM DATETIME,
        EXECUTOR VARCHAR(100),
        PRIMARY KEY (HID)
    ) ENGINE=INNODB DEFAULT CHARSET=utf8;
    
    CREATE TABLE TS_CHARTS_INFO (
        CHART_ID BIGINT NOT NULL AUTO_INCREMENT,
        CHART_NAME LONGTEXT,
        CHART_TYPE DECIMAL(22,0),
        CHART_DESC LONGTEXT,
        BELONG_LINK DECIMAL(22,0),
        CHART_USE LONGTEXT,
        KEY_FIELD LONGTEXT,
        FREQUENCE_TM DECIMAL(22,0),
        JS_NAME VARCHAR(100),
        XTYPE VARCHAR(100),
        PRIMARY KEY (CHART_ID)
    ) ENGINE=INNODB DEFAULT CHARSET=utf8;

